### ISSUE TITLE
flash_attn not found when using docker, and Alibaba-NLP/gte-Qwen2-1.5B-instruct

### ISSUE THREAD

**Issue by yaronr** [michaelfeil/infinity#308]
### System Info

Using docker latest (July 21st), with the following params:
v2   --port 8000 	--model-id Alibaba-NLP/gte-Qwen2-1.5B-instruct --model-id jinaai/jina-embeddings-v2-base-en

(note, jina-embeddings on its own works fine).

### Information

- [X] Docker
- [ ] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```
ERROR:    Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/app/infinity_emb/infinity_server.py", line 59, in lifespan
    app.engine_array = AsyncEngineArray.from_args(engine_args_list)  # type: ignore
  File "/app/infinity_emb/engine.py", line 256, in from_args
    return cls(engines=tuple(engines))
  File "/app/infinity_emb/engine.py", line 64, in from_args
    engine = cls(**engine_args.to_dict(), _show_deprecation_warning=False)
  File "/app/infinity_emb/engine.py", line 50, in __init__
    self._model, self._min_inference_t, self._max_inference_t = select_model(
  File "/app/infinity_emb/inference/select_model.py", line 65, in select_model
    loaded_engine = unloaded_engine.value(engine_args=engine_args)
  File "/app/infinity_emb/transformer/embedder/sentence_transformer.py", line 55, in __init__
    super().__init__(
  File "/app/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 287, in __init__
    modules = self._load_sbert_model(
  File "/app/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 1487, in _load_sbert_model
    module = Transformer(model_name_or_path, cache_dir=cache_folder, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 54, in __init__
    self._load_model(model_name_or_path, config, cache_dir, **model_args)
  File "/app/.venv/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 85, in _load_model
    self.auto_model = AutoModel.from_pretrained(
  File "/app/.venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 550, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/app/.venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 501, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/app/.venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 326, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/app/.venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 181, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`
```

### Expected behavior

Expected: no error
Actual: error 
J

**Comment by yaronr** [comment]
Thank you. 
Can this be added to the default docker image?
I prefer to stick with 'official' releases.

**Comment by michaelfeil** [comment]
#17 #306 #

**Comment by michaelfeil** [comment]
Adding it to the docker image results in a ~130mb increase.

**Comment by michaelfeil** [comment]
Fixed. FA2 is not even used efficently in this implementation, they could have also used `F.sdpa`. 

I created a special release with FA2 wheels installed in the docker file. Does this work?

```
docker run -it michaelf34/infinity:0.0.52-fa  v2 --port 8000 --model-id Alibaba-NLP/gte-Qwen2-1.5B-instruct 
```

**Comment by yaronr** [comment]
@michaelfeil you rock!
1/ IMO, 134mb is nothing - I would recommend for everyone (including yourself) to keep it simple, and have only one Docker as much as possible (wait until you find dependencies that are in the GBs for having multiple artifacts
2/ else - could you please create a ':latest-fa' ?
3/ I'm giving it a go now, and will shortly report back.

**Comment by michaelfeil** [comment]
Problem is the automated CI. Flash-attn does not support pep517 builds (poetry) & `pip install flash_attn` often fails -> wheel is directly `hacked` into this docker version.

**Comment by yaronr** [comment]
Just tested it, confirmed it solves the issue. Thank you so much.
Please consider (2) - create a :latest-fa release.
