### ISSUE TITLE
Get a AttributeError: torch._inductor.config.fx_graph_cache does not exist ERROR

### ISSUE THREAD

**Issue by tuobay** [michaelfeil/infinity#320]
### System Info

OS: Linux
MODEL: NO model
HARDWARE: 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:25:00.0 Off |                    0 |
| N/A   59C    P0   421W / 400W |  80922MiB / 81251MiB |     93%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000000:2B:00.0 Off |                    0 |
| N/A   73C    P0   403W / 400W |  80938MiB / 81251MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  On   | 00000000:65:00.0 Off |                    0 |
| N/A   74C    P0   404W / 400W |  80938MiB / 81251MiB |     94%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  On   | 00000000:6A:00.0 Off |                    0 |
| N/A   61C    P0   388W / 400W |  80242MiB / 81251MiB |     94%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

SORFTWARE: PyTorch version 2.1.2+cu118+infinity_emb0.0.52

```
❯ infinity_emb v2 --help
INFO     2024-07-24 09:53:12,021 datasets INFO: PyTorch version 2.1.2+cu118 available.                                                                                                       config.py:58
Traceback (most recent call last):
  File "/home/tuo/conda/envs/minicpmv/bin/infinity_emb", line 5, in <module>
    from infinity_emb.infinity_server import cli
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/__init__.py", line 20, in <module>
    from infinity_emb.engine import AsyncEmbeddingEngine, AsyncEngineArray  # noqa: E402
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/engine.py", line 7, in <module>
    from infinity_emb.inference import (
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/inference/__init__.py", line 1, in <module>
    from infinity_emb.inference.batch_handler import BatchHandler
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/inference/batch_handler.py", line 30, in <module>
    from infinity_emb.transformer.utils import get_lengths_with_tokenize
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/transformer/utils.py", line 10, in <module>
    from infinity_emb.transformer.embedder.ct2 import CT2SentenceTransformer
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/transformer/embedder/ct2.py", line 18, in <module>
    from infinity_emb.transformer.embedder.sentence_transformer import (
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/transformer/embedder/sentence_transformer.py", line 41, in <module>
    torch._inductor.config.fx_graph_cache = True
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/torch/_dynamo/config_utils.py", line 72, in __setattr__
    raise AttributeError(f"{self.__name__}.{name} does not exist")
AttributeError: torch._inductor.config.fx_graph_cache does not exist
❯ infinity_emb --help
INFO     2024-07-24 10:00:05,828 datasets INFO: PyTorch version 2.1.2+cu118 available.                                                                                                       config.py:58
Traceback (most recent call last):
  File "/home/togodpypy/conda/envs/minicpmv/bin/infinity_emb", line 5, in <module>
    from infinity_emb.infinity_server import cli
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/__init__.py", line 20, in <module>
    from infinity_emb.engine import AsyncEmbeddingEngine, AsyncEngineArray  # noqa: E402
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/engine.py", line 7, in <module>
    from infinity_emb.inference import (
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/inference/__init__.py", line 1, in <module>
    from infinity_emb.inference.batch_handler import BatchHandler
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/inference/batch_handler.py", line 30, in <module>
    from infinity_emb.transformer.utils import get_lengths_with_tokenize
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/transformer/utils.py", line 10, in <module>
    from infinity_emb.transformer.embedder.ct2 import CT2SentenceTransformer
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/transformer/embedder/ct2.py", line 18, in <module>
    from infinity_emb.transformer.embedder.sentence_transformer import (
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/infinity_emb/transformer/embedder/sentence_transformer.py", line 41, in <module>
    torch._inductor.config.fx_graph_cache = True
  File "/home/togodpypy/conda/envs/minicpmv/lib/python3.10/site-packages/torch/_dynamo/config_utils.py", line 72, in __setattr__
    raise AttributeError(f"{self.__name__}.{name} does not exist")
AttributeError: torch._inductor.config.fx_graph_cache does not exist
```

### Information

- [ ] Docker
- [X] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Just type 
`infinity_emb v2 --help`
can get the error

### Expected behavior

Just show the `help` command output

**Comment by michaelfeil** [comment]
Try torch=2.2
