### ISSUE TITLE
Support for ONNX mixedbread-ai/deepset-mxbai-embed-de-large-v1

### ISSUE THREAD

**Issue by ouz-m** [michaelfeil/infinity#330]
### Model description

Hello, 

I've been trying to run the mixedbread-ai/deepset-mxbai-embed-de-large-v1 with optimum engine in the docker image. 

Sadly  I am getting the following error.

```
2024-08-02 08:41:51.945159769 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running Gather node. Name:'/0/auto_model/embeddings/position_embeddings/Gather' Status Message: indices element out of data bounds, idx=514 must be within the inclusive range [-514,513]
ERROR:    Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/app/infinity_emb/infinity_server.py", line 59, in lifespan
    app.engine_array = AsyncEngineArray.from_args(engine_args_list)  # type: ignore
  File "/app/infinity_emb/engine.py", line 256, in from_args
    return cls(engines=tuple(engines))
  File "/app/infinity_emb/engine.py", line 64, in from_args
    engine = cls(**engine_args.to_dict(), _show_deprecation_warning=False)
  File "/app/infinity_emb/engine.py", line 50, in __init__
    self._model, self._min_inference_t, self._max_inference_t = select_model(
  File "/app/infinity_emb/inference/select_model.py", line 82, in select_model
    loaded_engine.warmup(batch_size=engine_args.batch_size, n_tokens=512)
  File "/app/infinity_emb/transformer/abstract.py", line 83, in warmup
    return run_warmup(self, inp)
  File "/app/infinity_emb/transformer/abstract.py", line 175, in run_warmup
    embed = model.encode_core(feat)
  File "/app/infinity_emb/transformer/embedder/optimum.py", line 88, in encode_core
    outputs = self.model(**onnx_input)
  File "/app/.venv/lib/python3.10/site-packages/optimum/modeling_base.py", line 95, in __call__
    return self.forward(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 1091, in forward
    onnx_outputs = self.model.run(None, onnx_inputs)
  File "/app/.venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gather node. Name:'/0/auto_model/embeddings/position_embeddings/Gather' Status Message: indices element out of data bounds, idx=514 must be within the inclusive range [-514,513]

```

I would appreciate some assistance, also please let me know if I can help with anything! 

Best, Ouz

### Open source status

- [X] The model implementation is available on transformers
- [X] The model weights are available on huggingface-hub
- [X] I verified that the model is currently not running in the lastest version `pip install infinity_emb[all] --upgrade`

**Comment by michaelfeil** [comment]
@ouz-m Thanks for opening!

please apply the fix from https://github.com/michaelfeil/infinity/issues/218 & open a PR for a shorter tokenizer config.

**Comment by ouz-m** [comment]
thanks! you can find the PR [here](https://huggingface.co/mixedbread-ai/deepset-mxbai-embed-de-large-v1/discussions/4). 

will close the issue after I test it, haven't had a chance yet. 👍🏻

**Comment by ouz-m** [comment]
It works, thanks again! @michaelfeil

**Comment by michaelfeil** [comment]
Awesome, great to hear @ouz-m
