### ISSUE TITLE
setting the pooling strategy - supported models? 

### ISSUE THREAD

**Issue by arbi-dev** [michaelfeil/infinity#42]
I receive the error below when trying to use the "hkunlp/instructor-xl" . It seems related to selection of the pooling mode.

Also, when running WhereIsAI_UAE-Large-V1 it seems to auto-select "MEAN" pooling whereas the model authors recommend "cls"

Are these models currently supported?

===traceback 
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO     2023-12-06 19:53:55,770 infinity_emb INFO:           select_model.py:17
         model=`hkunlp/instructor-xl` selected, using                           
         engine=`<class                                                         
         'infinity_emb.transformer.sentence_transformer.Sente                   
         nceTransformerPatched'>` and device=`None`                             
INFO     2023-12-06 19:53:55,772                       SentenceTransformer.py:66
         sentence_transformers.SentenceTransformer                              
         INFO: Load pretrained SentenceTransformer:                             
         hkunlp/instructor-xl                                                   
ERROR:    Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/app/infinity_emb/infinity_server.py", line 182, in _startup
    model, min_inference_t = select_model_to_functional(
  File "/app/infinity_emb/inference/select_model.py", line 21, in select_model_to_functional
    init_engine = engine.value(model_name_or_path, device=device.value)
  File "/app/infinity_emb/transformer/sentence_transformer.py", line 52, in __init__
    super().__init__(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "/app/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/app/.venv/lib/python3.10/site-packages/sentence_transformers/models/Pooling.py", line 120, in load
    return Pooling(**config)
TypeError: Pooling.__init__() got an unexpected keyword argument 'pooling_mode_weightedmean_tokens'

**Comment by michaelfeil** [comment]
Closing because of https://huggingface.co/hkunlp/instructor-base/discussions/6 - Instructor is just not compatible with `sentence-transformers`
