### ISSUE TITLE
v2 cli does not support loading models from local directory

### ISSUE THREAD

**Issue by bufferoverflow** [michaelfeil/infinity#477]
### System Info

docker image michaelf34/infinity:0.0.70

### Information

- [X] Docker + cli
- [ ] pip + cli
- [ ] pip + usage of Python interface

### Tasks

- [ ] An officially supported CLI command
- [ ] My own modifications

### Reproduction

1. `mkdir models && cd models && git clone https://huggingface.co/BAAI/bge-m3 && cd ..`
1. `docker run -it --gpus all  -v $PWD:/models  -p 8081:8081  michaelf34/infinity:0.0.70 v2  --model-id "/models/bge-m3"  --served-model-name bge-m3  --port 8081`
1. error message

```
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO     2024-11-22 07:54:41,359 infinity_emb INFO: Creating 1engines: engines=['bge-m3']                                                                                                infinity_server.py:92
INFO     2024-11-22 07:54:41,364 infinity_emb INFO: Anonymized telemetry can be disabled via environment variable `DO_NOT_TRACK=1`.                                                            telemetry.py:30
INFO     2024-11-22 07:54:41,373 infinity_emb INFO: model=`/models/bge-m3` selected, using engine=`torch` and device=`None`                                                                 select_model.py:64
ERROR:    Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/app/infinity_emb/infinity_server.py", line 96, in lifespan
    app.engine_array = AsyncEngineArray.from_args(engine_args_list)  # type: ignore
  File "/app/infinity_emb/engine.py", line 291, in from_args
    return cls(engines=tuple(engines))
  File "/app/infinity_emb/engine.py", line 70, in from_args
    engine = cls(**engine_args.to_dict(), _show_deprecation_warning=False)
  File "/app/infinity_emb/engine.py", line 55, in __init__
    self._model_replicas, self._min_inference_t, self._max_inference_t = select_model(
  File "/app/infinity_emb/inference/select_model.py", line 71, in select_model
    unloaded_engine = get_engine_type_from_config(engine_args)
  File "/app/infinity_emb/inference/select_model.py", line 36, in get_engine_type_from_config
    config_path = hf_hub_download(
  File "/app/.venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/app/.venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/models/bge-m3'. Use `repo_type` argument if needed.

ERROR:    Application startup failed. Exiting.

```

**Comment by bufferoverflow** [comment]
@michaelfeil It's basically just cloning the model to e.g. `/data/model/bge-m3` and then loading from there when starting infinity. This simplifies air gapped mode and makes the startup much faster especially if the model does not change but a new version of infinity is used.

**Comment by polyyarp** [comment]
Hi @bufferoverflow ,

I get the same error like yours. Can you share the docker command that works for local model directory?

Thanks.

**Comment by bufferoverflow** [comment]
```
cd /tmp
mkdir models && cd models && git clone https://huggingface.co/BAAI/bge-m3 && cd ..
docker run -it --gpus all  -v /tmp/models:/models  -p 8081:8081  michaelf34/infinity:0.0.70 v2  --model-id "/models/bge-m3"  --served-model-name bge-m3  --port 8081
```

**Comment by polyyarp** [comment]
Thanks @bufferoverflow!

**Comment by sfjhu** [comment]
I just found out about the update to v2 when I started testing something on our non-airgapped system today. The changes noted above are not working for me, maybe I'm overlooking something silly? Here's the relevant portions of my `docker-compose.yml`, `.env`, and dirlists for the referenced volumes.

- docker-compose.yml
```
 volumes:
      #edit .env file for these variables
      - ${EMBED_VOL}:/models
 command: [ "v2", "--model-id", "${INFINITY_EMBED_MODEL_ID}" ]
```

- .env
```
EMBED_VOL=/home/<intermediate_path>/models
INFINITY_EMBED_MODEL_ID=/models/e5-large-v2
```

- dirlist of the local `models` dir
```
drwxr-xr-x 2 **myuser domain^users 0 May  7  2024 all-MiniLM-L6-v2
drwxr-xr-x 2 **myuser domain^users 0 May  7  2024 bge-large-en-v1.5
drwxr-xr-x 2 **myuser domain^users 0 May  7  2024 bge-m3
drwxr-xr-x 2 **myuser domain^users 0 May  7  2024 bge-reranker-large
drwxr-xr-x 2 **myuser domain^users 0 Apr 29  2024 e5-large-v2
drwxr-xr-x 2 **myuser domain^users 0 Dec 11 14:28 lfs
drwxr-xr-x 2 **myuser domain^users 0 Dec 10 20:21 lt_models
drwxr-xr-x 2 **myuser domain^users 0 Jan  7 21:49 Qwen2.5-32B-Instruct
```

- dirlist of `e5-large-v2`
```
drwxr-xr-x 2 **myuser domain^users          0 Apr 29  2024 1_Pooling
-rwxr-xr-x 1 **myuser domain^users        616 Apr 29  2024 config.json
-rwxr-xr-x 1 **myuser domain^users       1125 Apr 29  2024 handler.py
-rwxr-xr-x 1 **myuser domain^users 1340616616 Apr 29  2024 model.safetensors
-rwxr-xr-x 1 **myuser domain^users        387 Apr 29  2024 modules.json
-rwxr-xr-x 1 **myuser domain^users 1340698349 Apr 29  2024 pytorch_model.bin
-rwxr-xr-x 1 **myuser domain^users      67842 Apr 29  2024 README.md
-rwxr-xr-x 1 **myuser domain^users         57 Apr 29  2024 sentence_bert_config.json
-rwxr-xr-x 1 **myuser domain^users        125 Apr 29  2024 special_tokens_map.json
-rwxr-xr-x 1 **myuser domain^users        314 Apr 29  2024 tokenizer_config.json
-rwxr-xr-x 1 **myuser domain^users     711396 Apr 29  2024 tokenizer.json
-rwxr-xr-x 1 **myuser domain^users     231508 Apr 29  2024 vocab.txt
```

**Comment by michaelfeil** [comment]
@sfjhu Can you make sure that the e5-large-v2 is a cloned git repo (from huggingface)

**Comment by sfjhu** [comment]
Just checked, it is

```
origin  https://huggingface.co/intfloat/e5-large-v2 (fetch)
origin  https://huggingface.co/intfloat/e5-large-v2 (push)
```

**Comment by wirthual** [comment]
Can you verify the model folder is accessible from inside the container? Like using a plain ubuntu container and print out the models folder? 

e.g.:
```shell
docker run -it -v /home/<intermediate_path>/models:/models ubuntu:22.04 ls -ahl /models/
```

**Comment by sfjhu** [comment]
Yup, that was it! That's really odd, I didn't change anything about my setup form the pre-v2 images. The directory that was originally mounted in to Infinity is a network drive mounted to the Docker host Ubuntu 22.04 machine via cfis-utils with these parameters:

`sudo mount -t cifs -o username=$USER,uid=$(id -u),gid=$(id -g),forceuid,forcegid //path/to/network/drive /path/on/docker/host` 

I can definitely access it directly on the host and, until v2, was able to access it for serving in Infinity.

Thanks for the assist, since e5 isn't super big, I just moved it directly onto my host machine and it's working fine from there.
