### ISSUE TITLE
Runtime Error with Alibaba-NLP/gte-multilingual-reranker-base with docker

### ISSUE THREAD

**Issue by uabbas** [michaelfeil/infinity#491]
### System Info

Following docker command gives a runtime error:
```
docker run --env CUDA_VISIBLE_DEVICES='2' -v $pwd/data:/app/.cache -p "7997":"7997" \
michaelf34/infinity:0.0.72 \
v2 --model-id Alibaba-NLP/gte-multilingual-reranker-base --revision "main" --dtype bfloat16 --batch-size 32 --device cuda --engine torch --port 7997
```
INFO:     Waiting for application startup.
INFO     2024-12-07 15:15:57,874 infinity_emb INFO:        infinity_server.py:92
         Creating 1engines:
         engines=['Alibaba-NLP/gte-multilingual-reranker-b
         ase']
INFO     2024-12-07 15:15:57,877 infinity_emb INFO: Anonymized   telemetry.py:30
         telemetry can be disabled via environment variable
         `DO_NOT_TRACK=1`.
INFO     2024-12-07 15:15:57,882 infinity_emb INFO:           select_model.py:64
         model=`Alibaba-NLP/gte-multilingual-reranker-base`
         selected, using engine=`torch` and device=`cuda`
ERROR:    Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/app/infinity_emb/infinity_server.py", line 96, in lifespan
    app.engine_array = AsyncEngineArray.from_args(engine_args_list)  # type: ignore
  File "/app/infinity_emb/engine.py", line 291, in from_args
    return cls(engines=tuple(engines))
  File "/app/infinity_emb/engine.py", line 70, in from_args
    engine = cls(**engine_args.to_dict(), _show_deprecation_warning=False)
  File "/app/infinity_emb/engine.py", line 55, in __init__
    self._model_replicas, self._min_inference_t, self._max_inference_t = select_model(
  File "/app/infinity_emb/inference/select_model.py", line 81, in select_model
    loaded_engine = unloaded_engine.value(engine_args=engine_args_copy)
  File "/app/infinity_emb/transformer/crossencoder/torch.py", line 54, in __init__
    super().__init__(
  File "/app/.venv/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 104, in __init__
    self.model = AutoModelForSequenceClassification.from_pretrained(
  File "/app/.venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 559, in from_pretrained
    return model_class.from_pretrained(
  File "/app/.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3997, in from_pretrained
    if metadata.get("format") == "pt":
AttributeError: 'NoneType' object has no attribute 'get'

ERROR:    Application startup failed. Exiting.
```

```

### Information

- [X] Docker + cli
- [ ] pip + cli
- [ ] pip + usage of Python interface

### Tasks

- [X] An officially supported CLI command
- [ ] My own modifications

### Reproduction

Code sample provided in the description.

**Comment by uabbas** [comment]
@michaelfeil  I am using exaxtly that and, that is what is failing.  I tried moving to the latest version of infinity `0.0.72` ,  but did not help.

**Comment by uabbas** [comment]
@michaelfeil  Thanks for your assistance.
